### ISSUE TITLE
Лишние метрики считаются при добавлении новой метрики

### ISSUE THREAD

**Issue by r3code** [vseinstrumentiru/vector.dev-metrics-to-logs-helper#1]
**Что не так.**
Добавили новое определение метрики:

```
vi_kubedns_http:
    requests_total:
      metric_type: counter
      group_by_logfield: http_status_code
      label_logfield_mapping:
        vhost: "http_host"
        service_name: "service_name"
        k8s_cluster: "cluster_name"
        namespace: "namespace"
        method: "http_method"
        status: "http_status_code"
      event_selectors:
        - selector: входящие запросы по kubedns
          filter:
            namespace:
              eq: "web-show"
            http_host:
              re: ".*local"
```
После этого в ранее определенных метриках  vi_http_requests_total и vi_http_request_duration_seconds стали появляться серии метрик с path для которых не определены фильтры.

Ожидали, что добавление новой метрики со своим набором фильтров будет считать только для него подходящие логи и не затронет другие.
