### ISSUE TITLE
label_override заменяет значение и в соседних метриках

### ISSUE THREAD

**Issue by r3code** [vseinstrumentiru/vector.dev-metrics-to-logs-helper#6]
Если в условиях на поле указан regexp, который захватывает и все предыдущие фильтры событий метрики.   
То замена label_override будет выолняться во всех метриках, т.е. там где вы этого не ждете.
```
- selector: "Запросы комментариев к продукту"
            filter:
              Attributes."url.path":
                re: "^/goods/(.*?)/comments$"
                label_override: "/goods/:uuid/comments"
              ServiceName:
                eq: "myservice"
- selector: "Все остальные запросы"
            filter:
              Attributes."url.path":
                re: ".*"
                label_override: ":url_path"
              ServiceName:
                eq: "myservice"
```
Ожидается что для "Запросы комментариев к продукту" на выходе в path будет "/goods/:uuid/comments", а по факту получаем ":url_path"
